name: Bug Report
description: Post a bug report for this appllication
labels: [bug]
title: "[Bug] <title>"

body:
  - type: markdown
    attributes:
      value: |
        # Bug Report
        You can report bugs here or on our [Discord server](https://discord.gg/gcFTqq6Ee9) (Server rules apply)

        Please make sure to follow the Code of Conduct when making an issue here and do not make false issues. 
        Failiure to follow the Code of Conduct will result in moderation action.
        **Do not make dulplicate bug reports, check to see if your issue is already posted**
  
  - type: input
    id: discord
    attributes:
      label: Discord Account or email
      description: This is so we are able to contact you about the bug progress
      placeholder: username#0000 / hatsunemiku@gmail.com
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: What happens when the bug or crash occurs?
      description: Where does this bug or crash occur, when does it occur, etc.
      placeholder: The bug/crash happens sometimes when I do ..., causing this to not work/the app to crash. I think it happens because of ...
    validations:
      required: true

  - type: textarea
    id: expected-behaviour
    attributes:
      label: What is the expected behaviour?
      description: Simply detail what the expected behaviour is.
      placeholder: I expect the app to open the ... page instead of ..., it prevents me from doing ...
    validations:
      required: true

  - type: textarea
    id: steps-to-take
    attributes:
      label: How do you recreate this bug or crash?
      description: Give us a list of steps in order to recreate the bug or crash.
      placeholder: |
        1. Do ...
        2. Then ...
        3. Do this ..., ... and then ...
        4. Observe "the bug" or "the crash"
    validations:
      required: true

  - type: textarea
    id: crash-log
    attributes:
      label: Errors and proof
      description: Does the application throw any errors, if yes then what does it say? Otherwise feel free to attach screenshots or links here to help us with your bug report.
      placeholder: Error Info / Proof
    validations:
      required: false

  - type: checkboxes
    id: agreement-check
    attributes:
      label: Request Agreement
      description: Review the following below
      options:
        - label: I agree that this bug report is not a dulplicate and not spam and that all info provided is true.
          required: true
        - label: I have read the requirements for opening an issue above
          required: true
